### ISSUE TITLE
Geração de código krakatoa para declarações de método

### ISSUE THREAD

**Issue by guilhermejcgois** [Richsan/Krakacomp#2]
Está dando `NullPointerException` toda vez que chamamos `genKra` da `StatementList`.

**Comment by guilhermejcgois** [comment]
O stacktrace é algo como isso:

```
java.lang.NullPointerException
    at ast.MethodDec.genKra(MethodDec.java:48)
    at ast.MethodList.genKra(MethodList.java:42)
    at ast.KraClass.genKra(KraClass.java:125)
    at ast.Program.genKra(Program.java:21)
    at comp.Comp.compileProgram(Comp.java:266)
    at comp.Comp.run(Comp.java:68)
    at comp.Comp.main(Comp.java:10)
```
